### ISSUE TITLE
Cannot download package

### ISSUE THREAD

**Issue by ElvaWong** [almeidasilvaf/bears#1]
Hi, I cloud not download the package.

```
install.packages("remotes")
>Installing package into 'C:/Users/elvag/AppData/Local/R/win-library/4.3'
(as 'lib' is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/remotes_2.4.2.1.zip'
Content type 'application/zip' length 398611 bytes (389 KB)
downloaded 389 KB

package 'remotes' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\elvag\AppData\Local\Temp\RtmpwPhh47\downloaded_packages
>

remotes::install_github("almeidasilvaf/bear")

>Downloading GitHub repo almeidasilvaf/bear@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/almeidasilvaf/bear/tarball/HEAD' failed
>
```

**Comment by almeidasilvaf** [comment]
You misspelled the package's name. It should have been:

```r
remotes::install_github("almeidasilvaf/bears")
```

**Comment by ElvaWong** [comment]
Thank you noticing my spelling mistake, but the correct code still doesn't work.

remotes::install_github("almeidasilvaf/bears")

>Downloading GitHub repo almeidasilvaf/bears@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/almeidasilvaf/bears/tarball/HEAD' failed
>

**Comment by almeidasilvaf** [comment]
I can't reproduce the issue on my machine. Some possible causes include:

1. Temporary problem with the GitHub servers (this has happened to me before when trying to install packages from GitHub)
2. Unstable connection
3. Problem with your installation of the __remotes__ package. 

Could you try to install __remotes__ again and rerun the installation code to see if it works?
